# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.
# Can also be triggered by a repository dispatch event.

name: Update .NET nanoFramework dependencies

on:
  schedule:
  # At 00:00 UTC every day.
  - cron:  '00 00 * * *'
  repository_dispatch:
    types: update-dependencies

env:
  NFBOT_GITHUB_ACTIONS: ${{ secrets.NFBOT_GITHUB_ACTIONS }}

jobs:
  update-dependencies:
    name: nanoFramework
    uses: nanoframework/nf-tools/.github/workflows/update-dependencies.yml@main
    with:
      solutionsToCheck: 'nanoFramework.Networking.Sntp.sln'
      githubAuth: $NFBOT_GITHUB_ACTIONS
